In [2]:
import tensorflow as tf
import experiment_utils as eu
import sys
sys.path.append('../')
from data_processing.stl10 import get_stl10
import config as conf
import importlib

In [3]:
importlib.reload(eu)
ds, _ = get_stl10(batch_size=5, split='unlabelled')
ds_small = ds.take(5)
config = conf.get_eigenspace_experiment()
experiment = eu.Experiment(config=config)
experiment.train(ds_small, 'saved_model', epochs=3)

  0%|          | 0/5 [00:00<?, ?it/s]

tf.Tensor(
[[ 5.88339847e-03  1.70654505e-02  2.41341237e-02 -2.28520972e-03
  -1.12159126e-01  1.01351939e-01 -6.46331608e-02  6.07058639e-03
  -5.46013825e-02  1.44893406e-02  5.97705618e-02 -9.05917585e-02
   1.38551686e-02 -4.47567366e-02 -2.93578692e-02 -3.25455121e-03
   3.11925914e-02 -4.97629605e-02 -1.40351532e-02  1.05039284e-01
   7.71456435e-02  8.50872323e-03  1.27790973e-01  3.62950750e-02
  -7.82959536e-02 -1.51776895e-03 -1.82259381e-02 -5.41399829e-02
   7.27257831e-03 -1.58093460e-02  6.05338067e-02  1.68040693e-01
  -6.58932254e-02 -6.48801699e-02 -1.13893539e-01  4.02753167e-02
  -3.27140130e-02 -1.82318866e-01 -1.31432682e-01 -7.02445954e-02
   7.26745874e-02 -5.87704666e-02 -2.66939327e-02  5.77942841e-03
   7.36189932e-02  9.84379277e-02  6.17853254e-02 -1.52298659e-01
   3.17606851e-02 -1.76394619e-02 -6.93107918e-02  3.60470079e-02
  -1.71249732e-02  3.10040191e-02  1.30853757e-01 -5.57126440e-02
   1.46798044e-01  5.06003387e-02  1.13956757e-01 -3.96982804e-02

 20%|██        | 1/5 [00:04<00:17,  4.26s/it]

tf.Tensor(
[[-1.97877293e+01 -2.03304043e+01  4.84515724e+01 -5.00308037e+01
   9.49294949e+00 -3.49792747e+01 -4.64903183e+01  3.34222832e+01
  -3.08804798e+01 -7.04099703e+00  2.20165901e+01 -1.57085323e+01
   2.39642644e+00 -6.17836876e+01 -1.63200397e+01  2.42831111e+00
  -7.02159500e+01 -2.84981804e+01 -4.56417847e+01  3.19293156e+01
  -3.16691513e+01  3.69959373e+01  2.68558254e+01  1.35235891e+01
   3.65434570e+01 -6.96953735e+01  1.88282280e+01  2.08174348e+00
  -8.42826557e+00  3.75772057e+01  9.66294482e-02 -1.32695637e+01
   3.54393578e+01  3.15475159e+01 -1.71569939e+01 -2.28279381e+01
  -7.14884109e+01 -4.22848845e+00  2.53870316e+01 -1.91963234e+01
  -2.26078434e+01  1.13411865e+01 -1.99495411e+01  1.97759438e+01
   1.97187843e+01  3.42141876e+01  2.10375290e+01 -1.48625031e+01
   2.70643406e+01  2.60835342e+01  1.59629488e+01 -8.24698105e+01
   2.91773357e+01  2.04021912e+01  4.70033455e+01 -2.25087280e+01
  -4.16872072e+00 -2.70541439e+01  1.47047377e+01  3.02861862e+01

 40%|████      | 2/5 [00:06<00:09,  3.21s/it]

tf.Tensor(
[[ -2721.1038    -1306.4993     -111.138794  -4802.6553     -461.11163
   -7854.4233    -3536.02       9000.681      1437.7637    -6144.0083
    3521.2961    -8044.605       631.9759     -794.1182    -1790.6763
     919.3697    -7255.7173    -3418.3523    -5009.372      9226.486
   -2875.5256     3146.323      4251.665      2036.4116     6178.838
   -6885.633      2907.7534      451.02844    5120.673      3275.014
   -6619.6274     -241.71324    9638.108      4387.9077    -6742.5474
   -4982.4814    -3211.8125     3244.6035    -4130.3364    -7179.455
    1766.2687     1411.7859    -2620.6113    -3954.6787     3482.415
    1600.4696     4351.4707    -2872.3235     3138.4602    -1825.9467
   -2169.7344    -9191.052      4563.719       740.924      4356.342
   -3364.7651    -1730.6685    -4107.154      2889.8638     1670.8956
   -2157.1052    -5737.068      3451.9011    -6003.063       -99.14787
    9009.092     -4523.3384      195.33824   -5631.707     -2366.1804
   -2028.8947

 60%|██████    | 3/5 [00:08<00:05,  2.76s/it]

tf.Tensor(
[[-4.75572188e+04 -1.82148262e+04 -9.81430817e+01 -7.70365703e+04
  -1.83432520e+04 -1.38411453e+05 -7.20637891e+04  1.72090312e+05
   1.36706475e+04 -1.02548992e+05  4.18893242e+04 -1.29068375e+05
  -2.04708496e+03 -1.36439038e+03 -3.87313867e+04  2.22959668e+04
  -1.19502227e+05 -6.57340781e+04 -9.28712969e+04  1.39119391e+05
  -5.41832812e+04  4.71986172e+04  8.80471719e+04  2.34638984e+04
   1.17024469e+05 -1.00075891e+05  6.15464844e+04  4.93058594e+03
   1.02839727e+05  6.08202305e+04 -1.11811703e+05 -4.21690820e+03
   1.65099219e+05  4.05092070e+04 -1.10170789e+05 -8.10979688e+04
  -6.70279141e+04  5.95571094e+04 -6.11064180e+04 -1.25769406e+05
   4.00034062e+04  2.66854668e+04 -4.70176289e+04 -6.87798906e+04
   5.06072188e+04  3.53765469e+04  6.45354961e+04 -4.01038008e+04
   5.62511016e+04 -3.36056719e+04 -3.11689023e+04 -1.48661016e+05
   6.89892578e+04  4.85227734e+03  5.87847148e+04 -4.94974492e+04
  -1.24281133e+04 -5.95829219e+04  4.98898789e+04  3.74545977e+04

 80%|████████  | 4/5 [00:11<00:02,  2.59s/it]

tf.Tensor(
[[-7.44515938e+05 -2.89633625e+05  7.63567344e+04 -1.12862575e+06
  -3.43987312e+05 -2.11677975e+06 -1.24992262e+06  2.68806725e+06
   1.03934234e+05 -1.53845900e+06  5.28477688e+05 -1.86984225e+06
  -9.88445000e+04  4.87932959e+03 -6.89151875e+05  3.89806094e+05
  -1.80777775e+06 -1.05656388e+06 -1.45119738e+06  1.91917762e+06
  -8.10109188e+05  6.91563188e+05  1.39788088e+06  2.65562031e+05
   1.86460062e+06 -1.39504400e+06  9.98400250e+05  4.20825156e+04
   1.66326125e+06  9.70990062e+05 -1.67251150e+06 -1.22863875e+05
   2.49944075e+06  3.87831281e+05 -1.56330438e+06 -1.15829675e+06
  -1.03782938e+06  9.27023938e+05 -8.16565062e+05 -1.91308525e+06
   6.64978250e+05  4.34415656e+05 -7.72193938e+05 -9.85688250e+05
   7.22387750e+05  5.90128438e+05  9.32280188e+05 -6.07118062e+05
   8.60609562e+05 -4.61359562e+05 -4.32086594e+05 -2.25561700e+06
   9.64986062e+05  5.46496172e+04  8.22260000e+05 -6.53006375e+05
  -6.52400898e+04 -8.08718250e+05  7.56123375e+05  6.57295062e+05

  0%|          | 0/5 [00:00<?, ?it/s]

Epoch 000: Loss: 1.558
tf.Tensor(
[[ -6205863.5    -2349634.5     1142887.1    -9262668.     -3096880.5
  -17638704.    -11218477.     22637088.       504164.38  -12613154.
    3836334.8   -15344477.     -1140084.2      236044.7    -6147130.
    3576289.2   -15024971.     -8894933.    -12246392.     15111947.
   -6673474.      5634960.5    11857415.      1851660.6    15938443.
  -11095726.      8562344.       360301.88   14327743.      8214941.
  -13921613.     -1368066.6    20901486.      2320959.    -12516281.
   -9344184.     -8537275.      7790379.     -6327570.    -15953538.
    5993140.      3814920.8    -6704638.     -7966172.      5861501.
    5147539.5     7607846.     -5040072.      7218204.     -3693927.5
   -3393608.2   -18700424.      7638513.       446858.97    6566355.5
   -4888789.5       87296.016  -6312506.5     6354292.      5887069.
   -8418052.    -11895871.      8376337.    -15583196.     -1691604.
   17438086.     -8711801.      2608449.5   -14377788.     -775544

 20%|██        | 1/5 [00:03<00:13,  3.40s/it]

tf.Tensor(
[[-3.11584540e+07 -1.13229400e+07  7.44098950e+06 -4.64387120e+07
  -1.65551450e+07 -8.87215680e+07 -5.88758560e+07  1.14694944e+08
   1.72057188e+06 -6.26298840e+07  1.73946580e+07 -7.70454800e+07
  -6.64395000e+06  2.14527725e+06 -3.19624420e+07  1.91506260e+07
  -7.54314880e+07 -4.45104840e+07 -6.21569200e+07  7.31925120e+07
  -3.33393420e+07  2.82593780e+07  6.00509880e+07  8.39885100e+06
   8.15517680e+07 -5.41739800e+07  4.40393200e+07  2.14877725e+06
   7.36107840e+07  4.13985600e+07 -7.04749520e+07 -8.32453500e+06
   1.06016168e+08  8.83907500e+06 -6.15535680e+07 -4.61721120e+07
  -4.22522280e+07  3.94689960e+07 -3.04876660e+07 -8.03704560e+07
   3.20918240e+07  2.01412280e+07 -3.45306160e+07 -3.96560680e+07
   2.92839220e+07  2.64620020e+07  3.78925560e+07 -2.51085120e+07
   3.65745000e+07 -1.81946040e+07 -1.65878550e+07 -9.34804560e+07
   3.71358080e+07  2.34330350e+06  3.24698960e+07 -2.31191480e+07
   2.49863900e+06 -3.04358300e+07  3.22607780e+07  3.10078140e+07

 40%|████      | 2/5 [00:06<00:08,  2.98s/it]

tf.Tensor(
[[-1.13019696e+08 -3.86267240e+07  3.14266400e+07 -1.68265648e+08
  -6.25521000e+07 -3.21284544e+08 -2.19119264e+08  4.17154912e+08
   5.39277600e+06 -2.23991360e+08  5.83409920e+07 -2.79050400e+08
  -2.62991980e+07  1.04365040e+07 -1.17743088e+08  7.19917680e+07
  -2.72116544e+08 -1.59064192e+08 -2.26506432e+08  2.57786992e+08
  -1.19898488e+08  1.02553576e+08  2.18022000e+08  2.88294220e+07
   2.98811712e+08 -1.91967520e+08  1.62341600e+08  9.08171000e+06
   2.70712416e+08  1.49691472e+08 -2.56615648e+08 -3.36721160e+07
   3.86889760e+08  2.53094520e+07 -2.19360352e+08 -1.64649648e+08
  -1.51324768e+08  1.43306016e+08 -1.06698168e+08 -2.91036512e+08
   1.21708296e+08  7.57900640e+07 -1.26892600e+08 -1.43289456e+08
   1.05467416e+08  9.70208720e+07  1.36103072e+08 -8.92779680e+07
   1.33287296e+08 -6.46802240e+07 -5.92048640e+07 -3.36006432e+08
   1.31246072e+08  8.77908500e+06  1.16371480e+08 -8.09429760e+07
   1.43394380e+07 -1.06845072e+08  1.17952624e+08  1.15904040e+08

 60%|██████    | 3/5 [00:08<00:05,  2.63s/it]

tf.Tensor(
[[-2.58232928e+08 -8.24148080e+07  7.93272160e+07 -3.84016864e+08
  -1.48159200e+08 -7.29543872e+08 -5.07006080e+08  9.50236032e+08
   1.21676320e+07 -5.04665536e+08  1.25067680e+08 -6.34724736e+08
  -6.34675240e+07  2.85816660e+07 -2.70918432e+08  1.68269216e+08
  -6.15382272e+08 -3.55978272e+08 -5.17543232e+08  5.71660288e+08
  -2.72104640e+08  2.35733248e+08  4.94080928e+08  6.34500360e+07
   6.83744000e+08 -4.28868768e+08  3.74837280e+08  2.30066120e+07
   6.22438272e+08  3.37983136e+08 -5.87401600e+08 -8.55049520e+07
   8.85697856e+08  4.58124520e+07 -4.91570816e+08 -3.69356544e+08
  -3.41281632e+08  3.25966176e+08 -2.37817104e+08 -6.62110272e+08
   2.86395328e+08  1.77697680e+08 -2.92931488e+08 -3.25361984e+08
   2.38467664e+08  2.22655584e+08  3.04672800e+08 -1.97234064e+08
   3.03364800e+08 -1.43322384e+08 -1.35321776e+08 -7.56966784e+08
   2.93677888e+08  2.12800440e+07  2.63987712e+08 -1.82176560e+08
   4.13386400e+07 -2.37190688e+08  2.69763072e+08  2.70713088e+08

 80%|████████  | 4/5 [00:10<00:02,  2.50s/it]

tf.Tensor(
[[-9.65168192e+08 -2.86113600e+08  3.16393184e+08 -1.43867520e+09
  -5.63381760e+08 -2.70820890e+09 -1.90543270e+09  3.53439642e+09
   5.42259320e+07 -1.85715712e+09  4.44524864e+08 -2.36361677e+09
  -2.43293632e+08  1.16269240e+08 -1.01586349e+09  6.37621888e+08
  -2.27602125e+09 -1.30321114e+09 -1.93079859e+09  2.08542771e+09
  -1.01056186e+09  8.88998784e+08  1.82598515e+09  2.30031424e+08
   2.55271936e+09 -1.57630541e+09  1.40569971e+09  9.21034640e+07
   2.33425050e+09  1.24315469e+09 -2.19155968e+09 -3.42386656e+08
   3.30977946e+09  1.42654704e+08 -1.80366797e+09 -1.36247424e+09
  -1.26396608e+09  1.20891277e+09 -8.66384576e+08 -2.45746867e+09
   1.08915635e+09  6.78869888e+08 -1.09945101e+09 -1.21027072e+09
   8.86618048e+08  8.34669312e+08  1.12007130e+09 -7.10372160e+08
   1.12865536e+09 -5.19572384e+08 -5.06919904e+08 -2.78704000e+09
   1.07743309e+09  8.12287680e+07  9.84472896e+08 -6.75234368e+08
   1.77708768e+08 -8.68526080e+08  1.00792602e+09  1.02632576e+09

  0%|          | 0/5 [00:00<?, ?it/s]

Epoch 001: Loss: 0.416
tf.Tensor(
[[-2.44275046e+09 -6.92080448e+08  8.61704064e+08 -3.64692736e+09
  -1.45671642e+09 -6.83476787e+09 -4.85406874e+09  8.92523622e+09
   1.63442672e+08 -4.64584192e+09  1.07656154e+09 -5.96290816e+09
  -6.36348288e+08  3.12087104e+08 -2.57817062e+09  1.62308160e+09
  -5.72823398e+09 -3.24588134e+09 -4.88945562e+09  5.18723584e+09
  -2.55931802e+09  2.25294106e+09  4.59706522e+09  5.72155008e+08
   6.48111974e+09 -3.94409830e+09  3.58018560e+09  2.51621504e+08
   5.92521728e+09  3.12029338e+09 -5.54760243e+09 -9.11431936e+08
   8.39682662e+09  3.09845696e+08 -4.50252954e+09 -3.39862093e+09
  -3.19701274e+09  3.03665485e+09 -2.14111578e+09 -6.19920486e+09
   2.80492467e+09  1.75443072e+09 -2.80878106e+09 -3.06285107e+09
   2.23195162e+09  2.11934656e+09  2.81062784e+09 -1.75469837e+09
   2.84987008e+09 -1.28023270e+09 -1.28381171e+09 -6.98636442e+09
   2.70756403e+09  2.06188912e+08  2.47623987e+09 -1.71202573e+09
   4.99823488e+08 -2.16476467e+09  2.55586

 20%|██        | 1/5 [00:03<00:12,  3.14s/it]

tf.Tensor(
[[-4.56181299e+09 -1.24317645e+09  1.71105446e+09 -6.83040154e+09
  -2.76796672e+09 -1.27267308e+10 -9.09883392e+09  1.66167777e+10
   3.65242368e+08 -8.57987021e+09  1.93337997e+09 -1.10966927e+10
  -1.22059046e+09  5.96353728e+08 -4.82832640e+09  3.03970176e+09
  -1.06350592e+10 -5.97524941e+09 -9.13088102e+09  9.53958605e+09
  -4.79559885e+09  4.22094387e+09  8.52588339e+09  1.04603200e+09
   1.21299128e+10 -7.29673779e+09  6.70621389e+09  4.86923584e+08
   1.10762240e+10  5.76782643e+09 -1.03534029e+10 -1.77766682e+09
   1.56985774e+10  5.10502912e+08 -8.28834202e+09 -6.27747482e+09
  -5.98255514e+09  5.62609152e+09 -3.90771942e+09 -1.15335455e+10
   5.30353050e+09  3.33817856e+09 -5.28727347e+09 -5.71790029e+09
   4.15303347e+09  3.96820710e+09  5.20494950e+09 -3.19273139e+09
   5.29800499e+09 -2.32776269e+09 -2.40812723e+09 -1.29189181e+10
   5.03637606e+09  3.84083616e+08  4.59961446e+09 -3.21952333e+09
   1.00506150e+09 -3.99355750e+09  4.77591091e+09  4.97583155e+09

 40%|████      | 2/5 [00:05<00:07,  2.62s/it]

tf.Tensor(
[[-5.31584102e+09 -1.39005005e+09  2.08371507e+09 -8.00858982e+09
  -3.25757696e+09 -1.47790162e+10 -1.06061199e+10  1.92730911e+10
   4.96495776e+08 -9.89580083e+09  2.19873818e+09 -1.28860365e+10
  -1.44419610e+09  6.77794688e+08 -5.66005658e+09  3.56156979e+09
  -1.22949847e+10 -6.87870566e+09 -1.06324654e+10  1.09407826e+10
  -5.60746854e+09  4.97450957e+09  9.81830144e+09  1.17321984e+09
   1.41291110e+10 -8.42438912e+09  7.79713126e+09  5.58231296e+08
   1.29064284e+10  6.62054810e+09 -1.20573604e+10 -2.17248358e+09
   1.82696530e+10  5.29954240e+08 -9.49319885e+09 -7.29419213e+09
  -6.97158810e+09  6.51148032e+09 -4.45372314e+09 -1.33621402e+10
   6.20295936e+09  3.95345126e+09 -6.19262413e+09 -6.64438170e+09
   4.84055398e+09  4.64386714e+09  5.99629619e+09 -3.59406208e+09
   6.12867891e+09 -2.63964467e+09 -2.83515648e+09 -1.48706458e+10
   5.85159270e+09  4.40240480e+08  5.37178419e+09 -3.77721421e+09
   1.23604045e+09 -4.60366541e+09  5.56527360e+09  5.86395136e+09

 60%|██████    | 3/5 [00:07<00:04,  2.48s/it]

tf.Tensor(
[[-1.12066376e+10 -2.87865472e+09  4.61013453e+09 -1.69159782e+10
  -7.03600333e+09 -3.10214758e+10 -2.23502684e+10  4.04511171e+10
   1.15633293e+09 -2.06919311e+10  4.48767590e+09 -2.69960294e+10
  -3.10912128e+09  1.42939136e+09 -1.19954872e+10  7.52353741e+09
  -2.57246147e+10 -1.43311196e+10 -2.23904379e+10  2.26832568e+10
  -1.18680873e+10  1.05544212e+10  2.04902994e+10  2.39751885e+09
   2.97559532e+10 -1.75693824e+10  1.64316948e+10  1.14816218e+09
   2.71267205e+10  1.37428449e+10 -2.54000087e+10 -4.80110746e+09
   3.84470057e+10  9.64218304e+08 -1.96939448e+10 -1.52311521e+10
  -1.47084820e+10  1.36224778e+10 -9.23601408e+09 -2.80357171e+10
   1.31989443e+10  8.43590400e+09 -1.31503022e+10 -1.39688264e+10
   1.01595853e+10  9.79311309e+09  1.24663132e+10 -7.35952538e+09
   1.27776092e+10 -5.39867802e+09 -6.05148467e+09 -3.09734748e+10
   1.23337769e+10  9.38475456e+08  1.12851988e+10 -8.08113766e+09
   2.71724698e+09 -9.58005146e+09  1.16931901e+10  1.25142385e+10

 80%|████████  | 4/5 [00:10<00:02,  2.41s/it]

tf.Tensor(
[[-2.0106795e+10 -5.1686221e+09  8.7355443e+09 -3.0467197e+10
  -1.2906727e+10 -5.5637823e+10 -4.0187785e+10  7.2464245e+10
   2.2584374e+09 -3.6910174e+10  7.8467630e+09 -4.8243560e+10
  -5.7147679e+09  2.5442348e+09 -2.1654315e+10  1.3502937e+10
  -4.5993390e+10 -2.5553555e+10 -4.0245142e+10  4.0274326e+10
  -2.1470618e+10  1.8964517e+10  3.6621599e+10  4.1450596e+09
   5.3554991e+10 -3.1352930e+10  2.9549603e+10  1.9849687e+09
   4.8638005e+10  2.4444951e+10 -4.5595185e+10 -8.9340764e+09
   6.9072110e+10  1.5940026e+09 -3.4859794e+10 -2.7136516e+10
  -2.6563183e+10  2.4265009e+10 -1.6287360e+10 -5.0231738e+10
   2.3923116e+10  1.5311061e+10 -2.3821560e+10 -2.5083079e+10
   1.8182617e+10  1.7563421e+10  2.2218748e+10 -1.2958865e+10
   2.2750763e+10 -9.4955254e+09 -1.0954440e+10 -5.5135261e+10
   2.2275021e+10  1.6623272e+09  2.0097688e+10 -1.4695396e+10
   5.1292150e+09 -1.7039908e+10  2.0959314e+10  2.2754505e+10
  -2.9666091e+10 -3.7527593e+10  2.8048306e+10 -4.8066900e+

100%|██████████| 5/5 [00:12<00:00,  2.49s/it]


Epoch 002: Loss: 0.765


INFO:tensorflow:Assets written to: saved_model/assets


INFO:tensorflow:Assets written to: saved_model/assets


KeyboardInterrupt: 

In [ ]:
ds

<PrefetchDataset shapes: (None, 224, 224, 3), types: tf.float32>